
STATI = {
  "None": None,
  "REDAZIONE": 'REDAZIONE',
  "Redazione": 'REDAZIONE',
  "Bozza_Redazione": "REDAZIONE",
  "Bozza_Ricezione": "REDAZIONE",
  "Bozza": "REDAZIONE",
  "Ricezione": "REDAZIONE",
  "PARERI": 'PARERE',
  "Pareri": 'PARERE',
  "Visti": "VISTA",
  "Approvazione": 'APPROVAZIONE',
  "FIRMA": 'FIRMA',
  "Firma": 'FIRMA',
  "SPEDIZIONE_MANUALE": 'SPEDIZIONE_MANUALE',
  "ASPETTA_SPEDIZIONI": 'ASPETTA_SPEDIZIONI',
  "ASPETTA_SPEDIZIONE": 'ASPETTA_SPEDIZIONI',
  "CONTROLLO_SEGRETERIA": 'CONTROLLO_SEGRETERIA',
  "FINE": 'FINE',
  "Fine": 'FINE',
  "Fine_Emergenza_In": "FINE",
  "ATTENDI_JOBS": 'ATTENDI_JOBS',
  "Fine_Entrata": "FINE",
  "SMISTAMENTO": "SMISTAMENTO",
  "NUMERAZIONE": 'NUMERAZIONE',
  "Registrazione_Protocollo": 'REGISTRAZIONE_PROTOCOLLO',
  "AVVIA_SPEDIZIONI": 'AVVIA_SPEDIZIONI',
  "Ufficio_Atti": "UFFICIO_ATTI",
  "Direttore_Generale": "DG",
  "Direttore_Amministrativo": "DA",
  "Direttore_Scientifico": "DSC",
  "Direttore_Sanitario": "DS",
  "Direttore_Affari_Generali_Legali": "DAGL",
  "ANNULLATO": "ANNULLATO"
}
STATI_UFFICIO_ATTI = {
  "None": None,
  "sospesa": "SOSPESA",
  "Elaborata": "ELABORATA",
  "Non Rilevante": "NON_RILEVANTE",
  "da_valutare": "DA_VALUTARE"
}
TIPO_ALLEGATO = {
  "ANNESSO": "ANNESSO",
  "Annesso": "ANNESSO",
  "Annotazione": "ANNOTAZIONE",
  "ANNOTAZIONE": "ANNOTAZIONE",
  "ALLEGATO": "ALLEGATO",
  "FRONTESPIZIO": "FRONTESPIZIO",
  "TESTO_OMISSIS": "TESTO_OMISSIS",
  "TESTO": "TESTO",
  "STAMPA_UNICA_OMISSIS": "STAMPA_UNICA_OMISSIS",
  "STAMPA_UNICA": "STAMPA_UNICA",
  "REGISTRO_GIORNALIERO": "REGISTRO_GIORNALIERO"
}
SOTTOTIPO_ALLEGATO = {
  "Delibera No Omissis": "DELIBERA_NO_OMISSIS",
  "Delibera Omissis": "DELIBERA_OMISSIS",
  "Destinatari": "DESTINATARI",
  "Note_Documento": "NOTE_DOCUMENTO",
  "NoteDocumento": "NOTE_DOCUMENTO",
  "RicevutaAccettazionePec": "RICEVUTA_ACCETTAZIONE_PEC",
  "RicevutaConsegnaPec": "RICEVUTA_CONSEGNA_PEC",
  "RicevutaErrorePec": "RICEVUTA_ERRORE_PEC",
  "RicevutaMancataConsegnaPec": "RICEVUTA_MANCATA_CONSEGNA_PEC",
  "RicevutaSconosciutaPec": "RICEVUTA_SCONOSCIUTA_PEC",
  "Segnatura": "SEGNATURA",
  "Smistamento": "SMISTAMENTO",
  "destinatari": "DESTINATARI",
  "mittenti": "MITTENTI",
  "RELATA": "RELATA",
  "Bird": "BIRD",
  "SINTESI_TRASPARENZA": "SINTESI_TRASPARENZA",
  "LEGGE_190": "LEGGE_190"
}
RUOLO_ATTORE = {
  "ASSEGNATARIO_INTERNO": "ASSEGNATARIO_INTERNO",
  "Approvazione": "APPROVAZIONE",
  "Redazione": "REDAZIONE",
  "REDAZIONE": "REDAZIONE",
  "Ricezione": "RICEZIONE",
  "RICEZIONE": "RICEZIONE",
  "CONTROLLO_SEGRETERIA": "CONTROLLO_SEGRETERIA",
  "Direttore_Affari_Generali_Legali": "DIRETTORE_AFFARI_GENERALI_LEGALI",
  "Direttore_Amministrativo": "DIRETTORE_AMMINISTRATIVO",
  "Direttore_Generale": "DIRETTORE_GENERALE",
  "Direttore_Sanitario": "DIRETTORE_SANITARIO",
  "Direttore_Scientifico": "DIRETTORE_SCIENTIFICO",
  "Visore": "VISORE",
  "FIRMA": "FIRMA",
  "Firma": "FIRMA",
  "Visti": "VISTI",
  #"GESTORE_PEC": "segnaposto", Nel nuovo internauta non vogliamo i gestori pec come attori
  #"Gestore_Pec": "segnaposto", Saranno solo delle persone vedenti come gli utenti che hanno permesso su archivio
  "PARERI": "PARERI",
  "Pareri": "PARERI",
  "RESP_PROC": "RESPONSABILE_PROCEDIMENTO",
  "RESCRITTO": "RESCRITTO",
  "Responsabile_Procedimento": "RESPONSABILE_PROCEDIMENTO",
  "SPEDIZIONE_MANUALE": "SPEDIZIONE_MANUALE",
  "Spedizione_Manuale": "SPEDIZIONE_MANUALE",
  "Ufficio_Atti": "UFFICIO_ATTI",
  "Prima_Approvazione": "APPROVAZIONE",
  "Rescritto_AP": "RESCRITTO",
  "Raccolta_Approvazioni": "APPROVAZIONE",
  "Raccolta_Pareri_Pre_Firma": "PARERI",
  "Validazione_Segreteria": "CONTROLLO_SEGRETERIA",
  "Vedenza_Emergenza": "VEDENZA_EMERGENZA",
  "Bozza_Redazione": "REDAZIONE",
  "Bozza_Ricezione": "REDAZIONE",
  "RESPONSABILE": "RESPONSABILE",
  "SEGRETERIA": "SEGRETARIO",
  "ASSEGNAZIONE": "ASSEGNATARIO"
}
